project:
  type: website

website:
  title: Silas Principe
  navbar:
    logo: images/logo.png
    right:
      - href: index.qmd
        text: Início
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
  search: false

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: false

include-in-header:
  - text: |
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=DM+Serif+Display:ital@0;1&display=swap" rel="stylesheet">
  - material-symbols.html
mainfont: DM Sans

